/** Every API path, relative to `/api/v1`. */
export const API_PATHS = {
  AUTH_REGISTER: '/auth/register',
  AUTH_LOGIN: '/auth/login',
  AUTH_REFRESH: '/auth/refresh',
  AUTH_LOGOUT: '/auth/logout',
  AUTH_ME: '/auth/me',
  AUTH_MFA_VERIFY: '/auth/mfa/verify',
  AUTH_REAUTH: '/auth/reauth',
  EMAIL_VERIFY: '/auth/email/verify',
  EMAIL_RESEND: '/auth/email/resend',
  PASSWORD_FORGOT: '/auth/password/forgot',
  PASSWORD_RESET: '/auth/password/reset',
  PASSWORD_CHANGE: '/auth/password/change',
  MFA_STATUS: '/auth/mfa',
  MFA_TOTP_SETUP: '/auth/mfa/totp/setup',
  MFA_TOTP_CONFIRM: '/auth/mfa/totp/confirm',
  MFA_DISABLE: '/auth/mfa/disable',
  MFA_RECOVERY_CODES: '/auth/mfa/recovery-codes',
  SESSIONS: '/auth/sessions',
  session: (id: string) => `/auth/sessions/${encodeURIComponent(id)}`,
  SESSIONS_REVOKE_OTHERS: '/auth/sessions/revoke-others',
  SECURITY_EVENTS: '/auth/security-events',
  ACCOUNTS: '/accounts',
  account: (id: string) => `/accounts/${encodeURIComponent(id)}`,
  TRANSACTIONS: '/transactions',
  transaction: (id: string) => `/transactions/${encodeURIComponent(id)}`,
  ANALYTICS_SUMMARY: '/analytics/summary',
  ANALYTICS_MERCHANTS: '/analytics/merchants',
  CONNECTION_PROVIDERS: '/connections/providers',
  CONNECTIONS: '/connections',
  connection: (id: string) => `/connections/${encodeURIComponent(id)}`,
  linkToken: (provider: string) => `/connections/${provider}/link-token`,
  exchange: (provider: string) => `/connections/${provider}/exchange`,
  connectionSync: (id: string) => `/connections/${encodeURIComponent(id)}/sync`,
  connectionUpdateLinkToken: (id: string) => `/connections/${encodeURIComponent(id)}/update-link-token`,
  connectionReconnected: (id: string) => `/connections/${encodeURIComponent(id)}/reconnected`,
  CLIENT_CONFIG: '/meta/client-config',
} as const;
